apiVersion: v1
kind: Service
metadata:
  name: hashcracklab-service
spec:
  type: LoadBalancer
  selector:
    app: hashcracklab
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
